export const ROUTES = {
  home: "/",
  shop: "/shop",
  shopScarves: "/shop/scarves",
  shopHijabs: "/shop/hijabs",
  shopAbayas: "/shop/abayas",
  shopAccessories: "/shop/accessories",
  collections: "/collections",
  collection: (slug: string) => `/collections/${slug}` as const,
  product: (slug: string) => `/product/${slug}` as const,
  journal: "/journal",
  journalArticle: (slug: string) => `/journal/${slug}` as const,
  about: "/about",
  craftsmanship: "/about/craftsmanship",
  sustainability: "/about/sustainability",
  contact: "/contact",
  cart: "/cart",
  checkout: "/checkout",
  wishlist: "/wishlist",
  account: "/account",
  login: "/account/login",
  register: "/account/register",
  search: "/search",
  privacy: "/privacy",
  terms: "/terms",
  shipping: "/shipping",
  returns: "/returns",
  faq: "/faq",
} as const;

export type RouteKey = keyof typeof ROUTES;
